FROM ubuntu:18.04
MAINTAINER mikebentley15@gmail.com

# Setup UTF-8 locale and other dependencies
RUN apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
      curl \
      dbus-x11 \
      gnupg2 \
      libpython3-dev \
      locales \
      lsb-release \
      python3-argcomplete \
      wget \
      && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' LC_ALL='en_US.UTF-8'

# Add the ROS 2 apt repository
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | \
      apt-key add - && \
    echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu bionic main" \
      > /etc/apt/sources.list.d/ros2-latest.list

# Install ROS 2
RUN apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install ros-eloquent-desktop && \
    rm -rf /var/lib/apt/lists/*

### Download and unpack ROS 2
##RUN wget https://github.com/ros2/ros2/releases/download/release-eloquent-20200124/ros2-eloquent-20200124-linux-bionic-amd64.tar.bz2 && \
##    tar --bzip2 -xvf ros2-eloquent-20200124-linux-bionic-amd64.tar.bz2 \
##      --directory /opt/ && \
##    rm /ros2-eloquent-20200124-linux-bionic-amd64.tar.bz2

# Initialize rosdep
RUN apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
      python-rosdep \
      && \
    rm -rf /var/lib/apt/lists/* && \
    rosdep init

# Install missing dependencies
RUN apt-get -y update && \
    rosdep update && \
    DEBIAN_FRONTEND=noninteractive rosdep install \
      --from-paths /opt/ros/eloquent/share \
      --ignore-src \
      --rosdistro eloquent \
      -y \
      --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 osrf_testing_tools_cpp poco_vendor rmw_connext_cpp rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp rti-connext-dds-5.3.1 tinyxml_vendor tinyxml2_vendor urdfdom urdfdom_headers" && \
    rosdep fix-permissions && \
    rm -rf /root/.ros && \
    rm -rf /var/lib/apt/lists/*

# Setup bash environment
RUN echo 'if [ -f "/opt/ros/eloquent/setup.bash" ]; then' >> /etc/bash.bashrc && \
    echo '  source "/opt/ros/eloquent/setup.bash"'        >> /etc/bash.bashrc && \
    echo 'fi'                                           >> /etc/bash.bashrc

# Have some way to know what kind of docker container we're in
RUN echo "ros2" > /etc/docker-name
