[dev_build]
compiler_name = 'g++'
optimization_level = '-O3'
switches = '-mavx -mavx2 -mfma -fsignaling-nans -frounding-math -freciprocal-math -fno-trapping-math -fmerge-all-constants -ffp-contract=on -ffinite-math-only -fexcess-precision=fast -fcx-limited-range -fcx-fortran-rules -fassociative-math'

[ground_truth]
compiler_name = 'g++'
optimization_level = '-O2'
switches = ''

[[compiler]]
binary = 'g++'
name = 'g++'
type = 'gcc'
# compiler-specific flags always used
fixed_compile_flags = ''
fixed_link_flags = ''
# search space of optimization levels
optimization_levels = [
  '-O0',
  '-O1',
  '-O2',
  '-O3',
]
switches_list = [
  '-fassociative-math',
  '-fcx-fortran-rules',
  '-fcx-limited-range',
  '-fexcess-precision=fast',
  '-ffinite-math-only',
  '-ffloat-store',
  '-ffp-contract=on',
  '-fmerge-all-constants',
  '-fno-trapping-math',
  '-freciprocal-math',
  '-frounding-math',
  '-fsignaling-nans',
  '-funsafe-math-optimizations',
  '-mavx',
  '-mavx2 -mfma',
  '-mfpmath=sse -mtune=native',
  ''
]

[[compiler]]
binary = 'clang++'
name = 'clang++'
type = 'clang'
fixed_compile_flags = ''
fixed_link_flags = ''
optimization_levels = [
  '-O0',
  '-O1',
  '-O2',
  '-O3',
]
switches_list = [
  '-fassociative-math',
  '-fexcess-precision=fast',
  '-fexcess-precision=standard',
  '-ffinite-math-only',
  '-ffloat-store',
  '-ffp-contract=on',
  '-fmerge-all-constants',
  '-fno-trapping-math',
  '-freciprocal-math',
  '-frounding-math',
  '-fsignaling-nans',
  '-fsingle-precision-constant',
  '-funsafe-math-optimizations',
  '-march=core-avx2',
  '-mavx',
  '-mavx2 -mfma',
  '-mfpmath=sse -mtune=native',
  ''
]
